version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "ohpsa-webapp"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - cd frontend/webapp/
            - npm install yarn -g
            - yarn install
    build:
        commands:
            - echo Build started on `date`
            - ng build --env=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '/frontend/webapp/**/*'
    base-directory: 'dist*'
    discard-paths: yes